### ISSUE TITLE
Please do not use paste.ubuntu.com

### ISSUE THREAD

**Issue by rfinnie** [XBMC-Addons/script.kodi.loguploader#2]
It appears this addon was originally written for easily uploading logs by Kodi users when e.g. making a forum post (https://kodi.wiki/view/Log_file/Easy).  That by itself would have been acceptable (though programs which post to pastebin.ubuntu.com are discouraged).

However, it appears many other addons are using this addon for automated uploading of very large dumps.  There were over 2 million Kodi posts, accounting for over 90% of the storage on the service, and was causing stability issues for the site, which was built for occasional small scale use by humans.

Kodi users and the public at large are still welcome to use pastebin.ubuntu.com manually, but please change this addon to use another service, or consider deploying a pastebin site specifically for the Kodi organization.

**Comment by MartijnKaijser** [comment]
Sorry to cause this trouble. I can already say that if its older than a month you're at least free to delete the content. We'll look into this asap.

**Comment by ronie** [comment]
thanx for the heads-up @rfinnie !

i have changed the addon to use ix.io from now on.
https://github.com/XBMC-Addons/script.kodi.loguploader/commit/1baba279e01fc30a2aebcf9f435d0a5b5476e4c3

this update will be pushed to all users of the addon within the next 24 hours.
should you still receive pastes from it after this period, feel free to block them.

i'm very, very sorry for the inconvenience this may have caused you.
